name: CI Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.8

    - name: format
      run: ./hack/check-format.sh
